import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { Container } from "react-bootstrap";
import Button from "../components/Button/Button";
import styles from "../styles/Home.module.css";
import Tab from "react-bootstrap/Tab";
import Tabs from "react-bootstrap/Tabs";
import Link from "next/link";
import WeProvide from "../Sections/We Provide/WeProvide";
import Benefits from "../Sections/Benefits/Benefits";
import Testimonials from "../Sections/Testimonials/Testimonials";
import DevPorocess from "../Sections/DevProcess/DevProcess";

export default function Home() {
  const [key, setKey] = useState("home");

  const handleChange = () => {
    setKey("profile");
  };
  return (
    <div>
      <Head>
        <title>React JS Development Services | Devox Software</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className={styles.main}>
          <Container>
            <div className={styles.main_container}>
              <div className={styles.title_wrapper}>
                <div>
                  <span className={styles.small_title}>React JS</span>
                </div>
                <div>
                  <span className={styles.main_title}>Development Company</span>
                </div>
              </div>
            </div>
            <p className={styles.description}>
              Looking for the right React JS development company that builds a
              standout user experience? Devox Software delivers stable and
              scalable solutions with dynamic user interfaces that combine
              robust functionality and supreme visuals. Explore the benefits of
              React.js that made it a leading front-end framework.
            </p>
            <div>
              <div className={styles.cta}>
                <div className={styles.ctaTagline}>Arrange a call</div>
                <Button
                  title={<img src={"/assets/images/arrowlight.svg"} />}
                  bgColor={"#a74ef4"}
                  height={50}
                  width={50}
                  textColor={"#fff"}
                  borderRadius={50}
                />
              </div>
            </div>
          </Container>
        </div>
        {/* We Provide section */}
        <div>
          <WeProvide />
        </div>
        {/* Benefits section */}
        <div>
          <Benefits />
        </div>
        {/* Testimonials section */}
        <div>
          <Testimonials />
        </div>
        {/* Dev section */}
        <div>
          <DevPorocess />
        </div>
      </div>
    </div>
  );
}
